//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDConfig) DeepCopyInto(out *ArgoCDConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDConfig.
func (in *ArgoCDConfig) DeepCopy() *ArgoCDConfig {
	if in == nil {
		return nil
	}
	out := new(ArgoCDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryConfig) DeepCopyInto(out *ContainerRegistryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryConfig.
func (in *ContainerRegistryConfig) DeepCopy() *ContainerRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenezioManager) DeepCopyInto(out *GenezioManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenezioManager.
func (in *GenezioManager) DeepCopy() *GenezioManager {
	if in == nil {
		return nil
	}
	out := new(GenezioManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenezioManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenezioManagerList) DeepCopyInto(out *GenezioManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenezioManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenezioManagerList.
func (in *GenezioManagerList) DeepCopy() *GenezioManagerList {
	if in == nil {
		return nil
	}
	out := new(GenezioManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenezioManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenezioManagerSpec) DeepCopyInto(out *GenezioManagerSpec) {
	*out = *in
	out.ArgoCDConfig = in.ArgoCDConfig
	out.GitConfig = in.GitConfig
	out.ContainerRegistryConfig = in.ContainerRegistryConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenezioManagerSpec.
func (in *GenezioManagerSpec) DeepCopy() *GenezioManagerSpec {
	if in == nil {
		return nil
	}
	out := new(GenezioManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenezioManagerStatus) DeepCopyInto(out *GenezioManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenezioManagerStatus.
func (in *GenezioManagerStatus) DeepCopy() *GenezioManagerStatus {
	if in == nil {
		return nil
	}
	out := new(GenezioManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitConfig) DeepCopyInto(out *GitConfig) {
	*out = *in
	out.Gitea = in.Gitea
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitConfig.
func (in *GitConfig) DeepCopy() *GitConfig {
	if in == nil {
		return nil
	}
	out := new(GitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitConfigGenezio) DeepCopyInto(out *GitConfigGenezio) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitConfigGenezio.
func (in *GitConfigGenezio) DeepCopy() *GitConfigGenezio {
	if in == nil {
		return nil
	}
	out := new(GitConfigGenezio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GiteaProvider) DeepCopyInto(out *GiteaProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GiteaProvider.
func (in *GiteaProvider) DeepCopy() *GiteaProvider {
	if in == nil {
		return nil
	}
	out := new(GiteaProvider)
	in.DeepCopyInto(out)
	return out
}
